### ISSUE TITLE
Wrong port in container-ports and ufw

### ISSUE THREAD

**Issue by Max-F-Helm** [hundehausen/monero-suite#10]
Hi,\
I noticed a potential mistake in the provided configurations:

The monerod command in the container is started with `--rpc-bind-port=18081` but both the `ports` section and ufw commands use port 18080.

**Comment by hundehausen** [comment]
Hi @Max-F-Helm,

`--rpc-bind-port=18081` should not be exposed via the internet or even in your LAN. For this we have `--rpc-restricted-bind-port=18089`, which is present int the ports section as in the ufw commands section.

But we could expose port 18081 onto the local machine with
```
ports:
    - 18080:18080 # p2port
    - 127.0.0.1:18081:18081 # unrestricted rpc port
    - 18089:18089 # restricted rpc port
```

**Comment by Max-F-Helm** [comment]
Yes, sorry, I mixed up the meaning ports.\
Closing this.
