### ISSUE TITLE
p2pool stats

### ISSUE THREAD

**Issue by lalanza808** [hundehausen/monero-suite#5]
as mentioned here, could add p2pool stats: https://github.com/hundehausen/monero-suite/pull/1#issuecomment-1760551285

looks like pretty easily scraped from local or remote - https://p2pool.io/api/

**Comment by hundehausen** [comment]
It would be awesome if you could create a second dashboard for P2Pool stats. Interesting would be the stats of the local P2Pool node and if mining is active we could scrape mining stats from https://p2pool.observer/api
